export const TypeHeading: string
export const typeHeading: string
export const level1: string
export const level2: string
export const level3: string
export const level4: string
export const isInverse: string
export const TypeStandfirst: string
export const typeStandfirst: string
export const TypeContainer: string
export const typeContainer: string
export const skeletonShimmerAnimation: string
