export const Home: string
export const home: string
export const HomeAlert: string
export const homeAlert: string
export const Stat: string
export const stat: string
export const StatBlock: string
export const statBlock: string
export const StatLine: string
export const statLine: string
export const StatList: string
export const statList: string
export const StatHash: string
export const statHash: string
export const StatBlockHeight: string
export const statBlockHeight: string
export const skeletonShimmerAnimation: string
